import React from 'react'
import Navbar from '../../components/Navbar/Navbar';
import Image from 'next/image';
import styles from './Containers.module.css';
import Background from './../Union.svg';
import Head from 'next/head';
export default function Containers(props : any) {
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar />
            {props.children}
            <Image className={styles.Background} src={Background} alt='Background'/>
        </>
    )
}
